runtime: php82
env: flex

runtime_config:
  operating_system: "ubuntu22"
  runtime_version: "8.3"
  document_root: public

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 1

resources:
  cpu: 2
  memory_gb: 4
  disk_size_gb: 100
